[package]
name = "s3-write-only-fs"
version = "0.1.0"
edition = "2018"

authors = [
    "TAKKT Industrial & Packaging GmbH <webshop-devops@kaiserkraft-europa.de>",
]
license = "Apache-2.0"

autobins = false
publish = false

[[bin]]
name = "s3-write-only-fs"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.34"
env_logger = "0.8.1"
fuse = { git = "https://github.com/zargony/fuse-rs/", rev = "39fde4a5c47ce370d228ac190f950bd835db7f47" }
libc = "0.2.80"
rusoto_core = "0.45.0"
rusoto_s3 = "0.45.0"
tokio = { version = "0.2.22", features = ["full"] }
